-- =================================================================
-- 1. TABEL WILAYAH
-- Menyimpan data master wilayah administratif yang dicakup.
-- =================================================================
CREATE TABLE public.wilayah (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    tipe TEXT NOT NULL CHECK (tipe IN ('kota', 'kabupaten')),
    provinsi TEXT NOT NULL,
    keywords TEXT[] -- Array kata kunci untuk pencocokan, misal: ["kab malang", "malang kabupaten"]
);

COMMENT ON TABLE public.wilayah IS 'Master data wilayah administratif yang dicakup oleh aplikasi.';
COMMENT ON COLUMN public.wilayah.keywords IS 'Kata kunci untuk membantu pencocokan hasil reverse geocoding.';

-- Aktifkan RLS
ALTER TABLE public.wilayah ENABLE ROW LEVEL SECURITY;

-- Policy: Publik bisa membaca semua data wilayah.
CREATE POLICY "Public can read wilayah" ON public.wilayah FOR SELECT
USING (true);


-- =================================================================
-- 2. TABEL ADMIN
-- Menyimpan data akun admin dan relasinya dengan wilayah.
-- =================================================================
CREATE TABLE public.admin (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email TEXT UNIQUE NOT NULL,
    wilayah_id BIGINT REFERENCES public.wilayah(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.admin IS 'Data admin yang terhubung dengan akun otentikasi Supabase.';
COMMENT ON COLUMN public.admin.wilayah_id IS 'Menentukan wilayah kerja admin.';

-- Aktifkan RLS
ALTER TABLE public.admin ENABLE ROW LEVEL SECURITY;

-- Policy: Admin bisa melihat data mereka sendiri.
CREATE POLICY "Admins can view their own data" ON public.admin FOR SELECT
USING (auth.uid() = id);


-- =================================================================
-- 3. FUNGSI HAVERSINE
-- Fungsi untuk menghitung jarak antara dua titik koordinat geografis.
-- =================================================================
CREATE OR REPLACE FUNCTION public.haversine(lat1 float, lon1 float, lat2 float, lon2 float)
RETURNS float AS $$
DECLARE
    R integer = 6371; -- Radius bumi dalam km
    dLat float;
    dLon float;
    a float;
    c float;
    d float;
BEGIN
    dLat = radians(lat2 - lat1);
    dLon = radians(lon2 - lon1);
    a = sin(dLat / 2) * sin(dLat / 2) +
        cos(radians(lat1)) * cos(radians(lat2)) *
        sin(dLon / 2) * sin(dLon / 2);
    c = 2 * atan2(sqrt(a), sqrt(1 - a));
    d = R * c;
    RETURN d;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION public.haversine(float, float, float, float) IS 'Menghitung jarak Haversine antara dua titik GPS dalam kilometer.';


-- =================================================================
-- 4. TABEL LAPORAN
-- Tabel utama untuk semua laporan yang masuk dari warga.
-- =================================================================
CREATE TABLE public.laporan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    
    -- Data Laporan
    judul TEXT NOT NULL,
    deskripsi TEXT,
    kategori TEXT,
    foto_url TEXT,

    -- Lokasi Kejadian (dari pin peta)
    pin_lat DOUBLE PRECISION NOT NULL,
    pin_lon DOUBLE PRECISION NOT NULL,
    alamat_lengkap TEXT, -- Hasil reverse geocoding
    kelurahan TEXT,
    kecamatan TEXT,
    kabupaten TEXT,
    provinsi TEXT,
    wilayah_id BIGINT REFERENCES public.wilayah(id),

    -- Metadata Audit GPS Pelapor
    reporter_lat DOUBLE PRECISION,
    reporter_lon DOUBLE PRECISION,
    reporter_accuracy FLOAT,
    reporter_gps_timestamp TIMESTAMPTZ,

    -- Kalkulasi Otomatis
    jarak_pelapor_km FLOAT, -- Jarak antara pin dan GPS pelapor
    risk_flag BOOLEAN DEFAULT false, -- True jika jarak > 50 km

    -- Consent
    disclaimer_agreed BOOLEAN NOT NULL,
    disclaimer_agreed_at TIMESTAMPTZ,

    -- Status Laporan
    status TEXT DEFAULT 'menunggu' NOT NULL,
    status_updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.laporan IS 'Tabel utama untuk menampung semua laporan dari warga.';
COMMENT ON COLUMN public.laporan.pin_lat IS 'Latitude dari pin yang ditandai di peta sebagai lokasi kejadian.';
COMMENT ON COLUMN public.laporan.pin_lon IS 'Longitude dari pin yang ditandai di peta sebagai lokasi kejadian.';
COMMENT ON COLUMN public.laporan.reporter_lat IS 'Latitude GPS pelapor saat mengirim form (hanya untuk audit).';
COMMENT ON COLUMN public.laporan.jarak_pelapor_km IS 'Jarak (km) antara lokasi kejadian dan lokasi pelapor saat submit.';
COMMENT ON COLUMN public.laporan.risk_flag IS 'Tanda risiko jika jarak pelapor > 50km dari lokasi kejadian.';
COMMENT ON COLUMN public.laporan.disclaimer_agreed IS 'Persetujuan disclaimer oleh pelapor.';


-- =================================================================
-- 5. TRIGGER UNTUK KALKULASI JARAK & RISIKO
-- Secara otomatis menghitung jarak dan flag risiko sebelum INSERT.
-- =================================================================
CREATE OR REPLACE FUNCTION public.calculate_distance_and_risk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.reporter_lat IS NOT NULL AND NEW.reporter_lon IS NOT NULL THEN
        NEW.jarak_pelapor_km = public.haversine(NEW.pin_lat, NEW.pin_lon, NEW.reporter_lat, NEW.reporter_lon);
        IF NEW.jarak_pelapor_km > 50 THEN
            NEW.risk_flag = true;
        ELSE
            NEW.risk_flag = false;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_distance_and_risk_before_insert
BEFORE INSERT ON public.laporan
FOR EACH ROW EXECUTE FUNCTION public.calculate_distance_and_risk();

COMMENT ON TRIGGER set_distance_and_risk_before_insert ON public.laporan IS 'Menghitung jarak dan flag risiko secara otomatis saat laporan baru dibuat.';


-- =================================================================
-- 6. ROW-LEVEL SECURITY (RLS) UNTUK TABEL LAPORAN
-- =================================================================
ALTER TABLE public.laporan ENABLE ROW LEVEL SECURITY;

-- Helper function untuk mendapatkan wilayah_id admin yang sedang login
CREATE OR REPLACE FUNCTION get_admin_wilayah_id()
RETURNS BIGINT AS $$
DECLARE
    wilayah_id_val BIGINT;
BEGIN
    SELECT wilayah_id INTO wilayah_id_val FROM public.admin WHERE id = auth.uid();
    RETURN wilayah_id_val;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Policy: Admin hanya bisa SELECT laporan dari wilayahnya.
CREATE POLICY "Admin can view reports from their own wilayah" ON public.laporan
FOR SELECT
TO authenticated
USING (wilayah_id = get_admin_wilayah_id());

-- Policy: Admin hanya bisa UPDATE laporan dari wilayahnya.
CREATE POLICY "Admin can update reports from their own wilayah" ON public.laporan
FOR UPDATE
TO authenticated
USING (wilayah_id = get_admin_wilayah_id());

-- Policy: User publik bisa INSERT laporan jika menyetujui disclaimer.
CREATE POLICY "Public can insert reports with disclaimer" ON public.laporan
FOR INSERT
WITH CHECK (disclaimer_agreed = true);

-- Policy: User publik bisa SELECT semua laporan (filtering di sisi client).
CREATE POLICY "Public can view all reports" ON public.laporan
FOR SELECT
USING (true);


-- =================================================================
-- 7. DATA AWAL (SEEDING)
-- Contoh data untuk wilayah dan admin.
-- =================================================================
INSERT INTO public.wilayah (nama, tipe, provinsi, keywords) VALUES
('Kota Malang', 'kota', 'Jawa Timur', '{"kota malang", "malang"}'),
('Kabupaten Malang', 'kabupaten', 'Jawa Timur', '{"kabupaten malang", "malang"}'),
('Kota Bekasi', 'kota', 'Jawa Barat', '{"kota bekasi", "bekasi"}');

-- Catatan: Seeding data admin harus dilakukan setelah user dibuat di Supabase Auth.
-- Contoh (ganti UUID dan email sesuai user Anda):
-- INSERT INTO public.admin (id, email, wilayah_id) VALUES
-- ('uuid-user-kotamalang', 'kotamalang@cepuin.id', (SELECT id FROM wilayah WHERE nama = 'Kota Malang')),
-- ('uuid-user-kabmalang', 'kabmalang@cepuin.id', (SELECT id FROM wilayah WHERE nama = 'Kabupaten Malang')),
-- ('uuid-user-kotabekasi', 'kotabekasi@cepuin.id', (SELECT id FROM wilayah WHERE nama = 'Kota Bekasi'));